#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Internal_API.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ICT_WHATSAPP")]
	public partial class DataClassesWADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_outbox(tbl_outbox instance);
    partial void Updatetbl_outbox(tbl_outbox instance);
    partial void Deletetbl_outbox(tbl_outbox instance);
    #endregion
		
		public DataClassesWADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ICT_WHATSAPPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_outbox> tbl_outboxes
		{
			get
			{
				return this.GetTable<tbl_outbox>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_outbox")]
	public partial class tbl_outbox : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _dateInsert;
		
		private System.DateTime _sendAfter;
		
		private string _destination;
		
		private int _isContact;
		
		private int _messageType;
		
		private string _messageText;
		
		private string _imagePath;
		
		private string _senderId;
		
		private string _sendError;
		
		private int _priority;
		
		private string _senderNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateInsertChanging(System.DateTime value);
    partial void OndateInsertChanged();
    partial void OnsendAfterChanging(System.DateTime value);
    partial void OnsendAfterChanged();
    partial void OndestinationChanging(string value);
    partial void OndestinationChanged();
    partial void OnisContactChanging(int value);
    partial void OnisContactChanged();
    partial void OnmessageTypeChanging(int value);
    partial void OnmessageTypeChanged();
    partial void OnmessageTextChanging(string value);
    partial void OnmessageTextChanged();
    partial void OnimagePathChanging(string value);
    partial void OnimagePathChanged();
    partial void OnsenderIdChanging(string value);
    partial void OnsenderIdChanged();
    partial void OnsendErrorChanging(string value);
    partial void OnsendErrorChanged();
    partial void OnpriorityChanging(int value);
    partial void OnpriorityChanged();
    partial void OnsenderNumberChanging(string value);
    partial void OnsenderNumberChanged();
    #endregion
		
		public tbl_outbox()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsert", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsert
		{
			get
			{
				return this._dateInsert;
			}
			set
			{
				if ((this._dateInsert != value))
				{
					this.OndateInsertChanging(value);
					this.SendPropertyChanging();
					this._dateInsert = value;
					this.SendPropertyChanged("dateInsert");
					this.OndateInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendAfter", DbType="DateTime NOT NULL")]
		public System.DateTime sendAfter
		{
			get
			{
				return this._sendAfter;
			}
			set
			{
				if ((this._sendAfter != value))
				{
					this.OnsendAfterChanging(value);
					this.SendPropertyChanging();
					this._sendAfter = value;
					this.SendPropertyChanged("sendAfter");
					this.OnsendAfterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				if ((this._destination != value))
				{
					this.OndestinationChanging(value);
					this.SendPropertyChanging();
					this._destination = value;
					this.SendPropertyChanged("destination");
					this.OndestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isContact", DbType="Int NOT NULL")]
		public int isContact
		{
			get
			{
				return this._isContact;
			}
			set
			{
				if ((this._isContact != value))
				{
					this.OnisContactChanging(value);
					this.SendPropertyChanging();
					this._isContact = value;
					this.SendPropertyChanged("isContact");
					this.OnisContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_messageType", DbType="Int NOT NULL")]
		public int messageType
		{
			get
			{
				return this._messageType;
			}
			set
			{
				if ((this._messageType != value))
				{
					this.OnmessageTypeChanging(value);
					this.SendPropertyChanging();
					this._messageType = value;
					this.SendPropertyChanged("messageType");
					this.OnmessageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_messageText", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string messageText
		{
			get
			{
				return this._messageText;
			}
			set
			{
				if ((this._messageText != value))
				{
					this.OnmessageTextChanging(value);
					this.SendPropertyChanging();
					this._messageText = value;
					this.SendPropertyChanged("messageText");
					this.OnmessageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagePath", DbType="VarChar(200)")]
		public string imagePath
		{
			get
			{
				return this._imagePath;
			}
			set
			{
				if ((this._imagePath != value))
				{
					this.OnimagePathChanging(value);
					this.SendPropertyChanging();
					this._imagePath = value;
					this.SendPropertyChanged("imagePath");
					this.OnimagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senderId
		{
			get
			{
				return this._senderId;
			}
			set
			{
				if ((this._senderId != value))
				{
					this.OnsenderIdChanging(value);
					this.SendPropertyChanging();
					this._senderId = value;
					this.SendPropertyChanged("senderId");
					this.OnsenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendError", DbType="VarChar(200)")]
		public string sendError
		{
			get
			{
				return this._sendError;
			}
			set
			{
				if ((this._sendError != value))
				{
					this.OnsendErrorChanging(value);
					this.SendPropertyChanging();
					this._sendError = value;
					this.SendPropertyChanged("sendError");
					this.OnsendErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int NOT NULL")]
		public int priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderNumber", DbType="VarChar(15)")]
		public string senderNumber
		{
			get
			{
				return this._senderNumber;
			}
			set
			{
				if ((this._senderNumber != value))
				{
					this.OnsenderNumberChanging(value);
					this.SendPropertyChanging();
					this._senderNumber = value;
					this.SendPropertyChanged("senderNumber");
					this.OnsenderNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
