#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Internal_API.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_OPT_POINTINTERNAL_KPT")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_BARGE(TBL_M_BARGE instance);
    partial void UpdateTBL_M_BARGE(TBL_M_BARGE instance);
    partial void DeleteTBL_M_BARGE(TBL_M_BARGE instance);
    partial void InsertTBL_M_TUGBOAT(TBL_M_TUGBOAT instance);
    partial void UpdateTBL_M_TUGBOAT(TBL_M_TUGBOAT instance);
    partial void DeleteTBL_M_TUGBOAT(TBL_M_TUGBOAT instance);
    partial void InsertTBL_M_JETTY(TBL_M_JETTY instance);
    partial void UpdateTBL_M_JETTY(TBL_M_JETTY instance);
    partial void DeleteTBL_M_JETTY(TBL_M_JETTY instance);
    partial void InsertTBL_M_MENU_APP(TBL_M_MENU_APP instance);
    partial void UpdateTBL_M_MENU_APP(TBL_M_MENU_APP instance);
    partial void DeleteTBL_M_MENU_APP(TBL_M_MENU_APP instance);
    partial void InsertTBL_M_USER(TBL_M_USER instance);
    partial void UpdateTBL_M_USER(TBL_M_USER instance);
    partial void DeleteTBL_M_USER(TBL_M_USER instance);
    partial void InsertTBL_T_BARGING_ONLINE(TBL_T_BARGING_ONLINE instance);
    partial void UpdateTBL_T_BARGING_ONLINE(TBL_T_BARGING_ONLINE instance);
    partial void DeleteTBL_T_BARGING_ONLINE(TBL_T_BARGING_ONLINE instance);
    partial void InsertTBL_R_CCTV(TBL_R_CCTV instance);
    partial void UpdateTBL_R_CCTV(TBL_R_CCTV instance);
    partial void DeleteTBL_R_CCTV(TBL_R_CCTV instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_OPT_POINTINTERNAL_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_APP_VERSION> TBL_M_APP_VERSIONs
		{
			get
			{
				return this.GetTable<TBL_M_APP_VERSION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_BARGE> TBL_M_BARGEs
		{
			get
			{
				return this.GetTable<TBL_M_BARGE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_TUGBOAT> TBL_M_TUGBOATs
		{
			get
			{
				return this.GetTable<TBL_M_TUGBOAT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_COMPANY> TBL_M_COMPANies
		{
			get
			{
				return this.GetTable<TBL_M_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<VW_BARGIN_ONLINE> VW_BARGIN_ONLINEs
		{
			get
			{
				return this.GetTable<VW_BARGIN_ONLINE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_JETTY> TBL_M_JETTies
		{
			get
			{
				return this.GetTable<TBL_M_JETTY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_MENU_APP> TBL_M_MENU_APPs
		{
			get
			{
				return this.GetTable<TBL_M_MENU_APP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER> TBL_M_USERs
		{
			get
			{
				return this.GetTable<TBL_M_USER>();
			}
		}
		
		public System.Data.Linq.Table<VW_USER> VW_USERs
		{
			get
			{
				return this.GetTable<VW_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_BARGING_ONLINE> TBL_T_BARGING_ONLINEs
		{
			get
			{
				return this.GetTable<TBL_T_BARGING_ONLINE>();
			}
		}
		
		public System.Data.Linq.Table<VW_ACTIVE_BARGING> VW_ACTIVE_BARGINGs
		{
			get
			{
				return this.GetTable<VW_ACTIVE_BARGING>();
			}
		}
		
		public System.Data.Linq.Table<VW_REQUEST_BARGING> VW_REQUEST_BARGINGs
		{
			get
			{
				return this.GetTable<VW_REQUEST_BARGING>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_IN_APP_NOTIF_POIN> TBL_T_IN_APP_NOTIF_POINs
		{
			get
			{
				return this.GetTable<TBL_T_IN_APP_NOTIF_POIN>();
			}
		}
		
		public System.Data.Linq.Table<VW_NOTIF_APPROVAL_BARGING> VW_NOTIF_APPROVAL_BARGINGs
		{
			get
			{
				return this.GetTable<VW_NOTIF_APPROVAL_BARGING>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_CCTV> TBL_R_CCTVs
		{
			get
			{
				return this.GetTable<TBL_R_CCTV>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_isVersionValid", IsComposable=true)]
		public System.Nullable<bool> cufn_isVersionValid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string version, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> fullVersion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string osName)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), version, fullVersion, osName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_get_list_jetty")]
		public ISingleResult<cusp_get_list_jettyResult> cusp_get_list_jetty()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_get_list_jettyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_get_barging_active")]
		public ISingleResult<cusp_get_barging_activeResult> cusp_get_barging_active()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_get_barging_activeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_get_barging_detail")]
		public ISingleResult<cusp_get_barging_detailResult> cusp_get_barging_detail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_get_barging_detailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_insertDataForInAppNotificationPOINS")]
		public int cusp_insertDataForInAppNotificationPOINS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_update_user_verification_poins")]
		public int cusp_update_user_verification_poins([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_UpdateStatusSelesaiBarging")]
		public int cusp_UpdateStatusSelesaiBarging()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_get_progress_barging_mobile")]
		public ISingleResult<cusp_get_progress_barging_mobileResult> cusp_get_progress_barging_mobile()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_get_progress_barging_mobileResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_get_last_senselog_realtime")]
		public ISingleResult<cusp_get_last_senselog_realtimeResult> cusp_get_last_senselog_realtime()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_get_last_senselog_realtimeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_avg_range_senselog")]
		public ISingleResult<cusp_avg_range_senselogResult> cusp_avg_range_senselog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate);
			return ((ISingleResult<cusp_avg_range_senselogResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_APP_VERSION")]
	public partial class TBL_M_APP_VERSION
	{
		
		private string _os_name;
		
		private string _app_version;
		
		private System.Nullable<System.DateTime> _release_date;
		
		public TBL_M_APP_VERSION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_os_name", DbType="NVarChar(50)")]
		public string os_name
		{
			get
			{
				return this._os_name;
			}
			set
			{
				if ((this._os_name != value))
				{
					this._os_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_version", DbType="NVarChar(50)")]
		public string app_version
		{
			get
			{
				return this._app_version;
			}
			set
			{
				if ((this._app_version != value))
				{
					this._app_version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_release_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> release_date
		{
			get
			{
				return this._release_date;
			}
			set
			{
				if ((this._release_date != value))
				{
					this._release_date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_BARGE")]
	public partial class TBL_M_BARGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BARGE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBARGEChanging(string value);
    partial void OnBARGEChanged();
    #endregion
		
		public TBL_M_BARGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARGE", DbType="VarChar(50)")]
		public string BARGE
		{
			get
			{
				return this._BARGE;
			}
			set
			{
				if ((this._BARGE != value))
				{
					this.OnBARGEChanging(value);
					this.SendPropertyChanging();
					this._BARGE = value;
					this.SendPropertyChanged("BARGE");
					this.OnBARGEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_TUGBOAT")]
	public partial class TBL_M_TUGBOAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TUG_BOAT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTUG_BOATChanging(string value);
    partial void OnTUG_BOATChanged();
    #endregion
		
		public TBL_M_TUGBOAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUG_BOAT", DbType="VarChar(50)")]
		public string TUG_BOAT
		{
			get
			{
				return this._TUG_BOAT;
			}
			set
			{
				if ((this._TUG_BOAT != value))
				{
					this.OnTUG_BOATChanging(value);
					this.SendPropertyChanging();
					this._TUG_BOAT = value;
					this.SendPropertyChanged("TUG_BOAT");
					this.OnTUG_BOATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_COMPANY")]
	public partial class TBL_M_COMPANY
	{
		
		private int _ID;
		
		private string _CUSTOMER;
		
		public TBL_M_COMPANY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER", DbType="VarChar(50)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BARGIN_ONLINE")]
	public partial class VW_BARGIN_ONLINE
	{
		
		private string _CUSTOMER;
		
		private string _BARGE;
		
		private string _TUG_BOAT;
		
		public VW_BARGIN_ONLINE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER", DbType="VarChar(50)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARGE", DbType="VarChar(50)")]
		public string BARGE
		{
			get
			{
				return this._BARGE;
			}
			set
			{
				if ((this._BARGE != value))
				{
					this._BARGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUG_BOAT", DbType="VarChar(50)")]
		public string TUG_BOAT
		{
			get
			{
				return this._TUG_BOAT;
			}
			set
			{
				if ((this._TUG_BOAT != value))
				{
					this._TUG_BOAT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_JETTY")]
	public partial class TBL_M_JETTY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAME;
		
		private System.Nullable<int> _CAPACITY;
		
		private System.Nullable<int> _DURATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCAPACITYChanging(System.Nullable<int> value);
    partial void OnCAPACITYChanged();
    partial void OnDURATIONChanging(System.Nullable<int> value);
    partial void OnDURATIONChanged();
    #endregion
		
		public TBL_M_JETTY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(1)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this.OnCAPACITYChanging(value);
					this.SendPropertyChanging();
					this._CAPACITY = value;
					this.SendPropertyChanged("CAPACITY");
					this.OnCAPACITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION", DbType="Int")]
		public System.Nullable<int> DURATION
		{
			get
			{
				return this._DURATION;
			}
			set
			{
				if ((this._DURATION != value))
				{
					this.OnDURATIONChanging(value);
					this.SendPropertyChanging();
					this._DURATION = value;
					this.SendPropertyChanged("DURATION");
					this.OnDURATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_MENU_APP")]
	public partial class TBL_M_MENU_APP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ICON;
		
		private string _NAMA;
		
		private string _URL_IOS;
		
		private string _URL_ANDROID;
		
		private string _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnICONChanging(string value);
    partial void OnICONChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnURL_IOSChanging(string value);
    partial void OnURL_IOSChanged();
    partial void OnURL_ANDROIDChanging(string value);
    partial void OnURL_ANDROIDChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_M_MENU_APP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICON", DbType="VarChar(MAX)")]
		public string ICON
		{
			get
			{
				return this._ICON;
			}
			set
			{
				if ((this._ICON != value))
				{
					this.OnICONChanging(value);
					this.SendPropertyChanging();
					this._ICON = value;
					this.SendPropertyChanged("ICON");
					this.OnICONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(MAX)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_IOS", DbType="VarChar(MAX)")]
		public string URL_IOS
		{
			get
			{
				return this._URL_IOS;
			}
			set
			{
				if ((this._URL_IOS != value))
				{
					this.OnURL_IOSChanging(value);
					this.SendPropertyChanging();
					this._URL_IOS = value;
					this.SendPropertyChanged("URL_IOS");
					this.OnURL_IOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_ANDROID", DbType="VarChar(MAX)")]
		public string URL_ANDROID
		{
			get
			{
				return this._URL_ANDROID;
			}
			set
			{
				if ((this._URL_ANDROID != value))
				{
					this.OnURL_ANDROIDChanging(value);
					this.SendPropertyChanging();
					this._URL_ANDROID = value;
					this.SendPropertyChanged("URL_ANDROID");
					this.OnURL_ANDROIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(MAX)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER")]
	public partial class TBL_M_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _EMAIL;
		
		private string _PASSWORD;
		
		private string _TELEPON;
		
		private string _NAMA;
		
		private string _FOTO;
		
		private string _OTP;
		
		private string _STATUS_LOGIN;
		
		private string _VERIFICATION_STATUS;
		
		private System.Nullable<int> _ID_COMPANY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnTELEPONChanging(string value);
    partial void OnTELEPONChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnFOTOChanging(string value);
    partial void OnFOTOChanged();
    partial void OnOTPChanging(string value);
    partial void OnOTPChanged();
    partial void OnSTATUS_LOGINChanging(string value);
    partial void OnSTATUS_LOGINChanged();
    partial void OnVERIFICATION_STATUSChanging(string value);
    partial void OnVERIFICATION_STATUSChanged();
    partial void OnID_COMPANYChanging(System.Nullable<int> value);
    partial void OnID_COMPANYChanged();
    #endregion
		
		public TBL_M_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPON", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEPON
		{
			get
			{
				return this._TELEPON;
			}
			set
			{
				if ((this._TELEPON != value))
				{
					this.OnTELEPONChanging(value);
					this.SendPropertyChanging();
					this._TELEPON = value;
					this.SendPropertyChanged("TELEPON");
					this.OnTELEPONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO", DbType="VarChar(MAX)")]
		public string FOTO
		{
			get
			{
				return this._FOTO;
			}
			set
			{
				if ((this._FOTO != value))
				{
					this.OnFOTOChanging(value);
					this.SendPropertyChanging();
					this._FOTO = value;
					this.SendPropertyChanged("FOTO");
					this.OnFOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTP", DbType="VarChar(50)")]
		public string OTP
		{
			get
			{
				return this._OTP;
			}
			set
			{
				if ((this._OTP != value))
				{
					this.OnOTPChanging(value);
					this.SendPropertyChanging();
					this._OTP = value;
					this.SendPropertyChanged("OTP");
					this.OnOTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_LOGIN", DbType="VarChar(50)")]
		public string STATUS_LOGIN
		{
			get
			{
				return this._STATUS_LOGIN;
			}
			set
			{
				if ((this._STATUS_LOGIN != value))
				{
					this.OnSTATUS_LOGINChanging(value);
					this.SendPropertyChanging();
					this._STATUS_LOGIN = value;
					this.SendPropertyChanged("STATUS_LOGIN");
					this.OnSTATUS_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFICATION_STATUS", DbType="VarChar(50)")]
		public string VERIFICATION_STATUS
		{
			get
			{
				return this._VERIFICATION_STATUS;
			}
			set
			{
				if ((this._VERIFICATION_STATUS != value))
				{
					this.OnVERIFICATION_STATUSChanging(value);
					this.SendPropertyChanging();
					this._VERIFICATION_STATUS = value;
					this.SendPropertyChanged("VERIFICATION_STATUS");
					this.OnVERIFICATION_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPANY", DbType="Int")]
		public System.Nullable<int> ID_COMPANY
		{
			get
			{
				return this._ID_COMPANY;
			}
			set
			{
				if ((this._ID_COMPANY != value))
				{
					this.OnID_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._ID_COMPANY = value;
					this.SendPropertyChanged("ID_COMPANY");
					this.OnID_COMPANYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_USER")]
	public partial class VW_USER
	{
		
		private int _ID;
		
		private string _EMAIL;
		
		private string _PASSWORD;
		
		private string _TELEPON;
		
		private string _NAMA;
		
		private string _FOTO;
		
		private string _OTP;
		
		private string _STATUS_LOGIN;
		
		private string _VERIFICATION_STATUS;
		
		private System.Nullable<int> _ID_COMPANY;
		
		private string _CUSTOMER;
		
		public VW_USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPON", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEPON
		{
			get
			{
				return this._TELEPON;
			}
			set
			{
				if ((this._TELEPON != value))
				{
					this._TELEPON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO", DbType="VarChar(MAX)")]
		public string FOTO
		{
			get
			{
				return this._FOTO;
			}
			set
			{
				if ((this._FOTO != value))
				{
					this._FOTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTP", DbType="VarChar(50)")]
		public string OTP
		{
			get
			{
				return this._OTP;
			}
			set
			{
				if ((this._OTP != value))
				{
					this._OTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_LOGIN", DbType="VarChar(50)")]
		public string STATUS_LOGIN
		{
			get
			{
				return this._STATUS_LOGIN;
			}
			set
			{
				if ((this._STATUS_LOGIN != value))
				{
					this._STATUS_LOGIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFICATION_STATUS", DbType="VarChar(50)")]
		public string VERIFICATION_STATUS
		{
			get
			{
				return this._VERIFICATION_STATUS;
			}
			set
			{
				if ((this._VERIFICATION_STATUS != value))
				{
					this._VERIFICATION_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPANY", DbType="Int")]
		public System.Nullable<int> ID_COMPANY
		{
			get
			{
				return this._ID_COMPANY;
			}
			set
			{
				if ((this._ID_COMPANY != value))
				{
					this._ID_COMPANY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER", DbType="VarChar(50)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_BARGING_ONLINE")]
	public partial class TBL_T_BARGING_ONLINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _ID_USER;
		
		private string _JETTY;
		
		private string _TUG_BOAT;
		
		private string _BARGE;
		
		private System.Nullable<int> _CAPACITY;
		
		private string _VESSEL;
		
		private System.Nullable<System.DateTime> _DATE_BOOKING;
		
		private System.Nullable<System.DateTime> _FINISH_BOOKING;
		
		private System.Nullable<int> _PROCESS_TIME;
		
		private System.Nullable<int> _START_TIME;
		
		private System.Nullable<int> _FINISH_TIME;
		
		private string _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnJETTYChanging(string value);
    partial void OnJETTYChanged();
    partial void OnTUG_BOATChanging(string value);
    partial void OnTUG_BOATChanged();
    partial void OnBARGEChanging(string value);
    partial void OnBARGEChanged();
    partial void OnCAPACITYChanging(System.Nullable<int> value);
    partial void OnCAPACITYChanged();
    partial void OnVESSELChanging(string value);
    partial void OnVESSELChanged();
    partial void OnDATE_BOOKINGChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_BOOKINGChanged();
    partial void OnFINISH_BOOKINGChanging(System.Nullable<System.DateTime> value);
    partial void OnFINISH_BOOKINGChanged();
    partial void OnPROCESS_TIMEChanging(System.Nullable<int> value);
    partial void OnPROCESS_TIMEChanged();
    partial void OnSTART_TIMEChanging(System.Nullable<int> value);
    partial void OnSTART_TIMEChanged();
    partial void OnFINISH_TIMEChanging(System.Nullable<int> value);
    partial void OnFINISH_TIMEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_T_BARGING_ONLINE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JETTY", DbType="VarChar(50)")]
		public string JETTY
		{
			get
			{
				return this._JETTY;
			}
			set
			{
				if ((this._JETTY != value))
				{
					this.OnJETTYChanging(value);
					this.SendPropertyChanging();
					this._JETTY = value;
					this.SendPropertyChanged("JETTY");
					this.OnJETTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUG_BOAT", DbType="VarChar(50)")]
		public string TUG_BOAT
		{
			get
			{
				return this._TUG_BOAT;
			}
			set
			{
				if ((this._TUG_BOAT != value))
				{
					this.OnTUG_BOATChanging(value);
					this.SendPropertyChanging();
					this._TUG_BOAT = value;
					this.SendPropertyChanged("TUG_BOAT");
					this.OnTUG_BOATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARGE", DbType="VarChar(50)")]
		public string BARGE
		{
			get
			{
				return this._BARGE;
			}
			set
			{
				if ((this._BARGE != value))
				{
					this.OnBARGEChanging(value);
					this.SendPropertyChanging();
					this._BARGE = value;
					this.SendPropertyChanged("BARGE");
					this.OnBARGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this.OnCAPACITYChanging(value);
					this.SendPropertyChanging();
					this._CAPACITY = value;
					this.SendPropertyChanged("CAPACITY");
					this.OnCAPACITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VESSEL", DbType="VarChar(200)")]
		public string VESSEL
		{
			get
			{
				return this._VESSEL;
			}
			set
			{
				if ((this._VESSEL != value))
				{
					this.OnVESSELChanging(value);
					this.SendPropertyChanging();
					this._VESSEL = value;
					this.SendPropertyChanged("VESSEL");
					this.OnVESSELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_BOOKING", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_BOOKING
		{
			get
			{
				return this._DATE_BOOKING;
			}
			set
			{
				if ((this._DATE_BOOKING != value))
				{
					this.OnDATE_BOOKINGChanging(value);
					this.SendPropertyChanging();
					this._DATE_BOOKING = value;
					this.SendPropertyChanged("DATE_BOOKING");
					this.OnDATE_BOOKINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_BOOKING", DbType="Date")]
		public System.Nullable<System.DateTime> FINISH_BOOKING
		{
			get
			{
				return this._FINISH_BOOKING;
			}
			set
			{
				if ((this._FINISH_BOOKING != value))
				{
					this.OnFINISH_BOOKINGChanging(value);
					this.SendPropertyChanging();
					this._FINISH_BOOKING = value;
					this.SendPropertyChanged("FINISH_BOOKING");
					this.OnFINISH_BOOKINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESS_TIME", DbType="Int")]
		public System.Nullable<int> PROCESS_TIME
		{
			get
			{
				return this._PROCESS_TIME;
			}
			set
			{
				if ((this._PROCESS_TIME != value))
				{
					this.OnPROCESS_TIMEChanging(value);
					this.SendPropertyChanging();
					this._PROCESS_TIME = value;
					this.SendPropertyChanged("PROCESS_TIME");
					this.OnPROCESS_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_TIME", DbType="Int")]
		public System.Nullable<int> START_TIME
		{
			get
			{
				return this._START_TIME;
			}
			set
			{
				if ((this._START_TIME != value))
				{
					this.OnSTART_TIMEChanging(value);
					this.SendPropertyChanging();
					this._START_TIME = value;
					this.SendPropertyChanged("START_TIME");
					this.OnSTART_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_TIME", DbType="Int")]
		public System.Nullable<int> FINISH_TIME
		{
			get
			{
				return this._FINISH_TIME;
			}
			set
			{
				if ((this._FINISH_TIME != value))
				{
					this.OnFINISH_TIMEChanging(value);
					this.SendPropertyChanging();
					this._FINISH_TIME = value;
					this.SendPropertyChanged("FINISH_TIME");
					this.OnFINISH_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ACTIVE_BARGING")]
	public partial class VW_ACTIVE_BARGING
	{
		
		private int _ID_USER;
		
		private string _JETTY;
		
		private string _CUSTOMER;
		
		private string _BARGE;
		
		private string _TUG_BOAT;
		
		private System.Nullable<int> _CAPACITY;
		
		private System.Nullable<System.DateTime> _DATE_BOOKING;
		
		public VW_ACTIVE_BARGING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JETTY", DbType="VarChar(50)")]
		public string JETTY
		{
			get
			{
				return this._JETTY;
			}
			set
			{
				if ((this._JETTY != value))
				{
					this._JETTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER", DbType="VarChar(50)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARGE", DbType="VarChar(50)")]
		public string BARGE
		{
			get
			{
				return this._BARGE;
			}
			set
			{
				if ((this._BARGE != value))
				{
					this._BARGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUG_BOAT", DbType="VarChar(50)")]
		public string TUG_BOAT
		{
			get
			{
				return this._TUG_BOAT;
			}
			set
			{
				if ((this._TUG_BOAT != value))
				{
					this._TUG_BOAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this._CAPACITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_BOOKING", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_BOOKING
		{
			get
			{
				return this._DATE_BOOKING;
			}
			set
			{
				if ((this._DATE_BOOKING != value))
				{
					this._DATE_BOOKING = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_REQUEST_BARGING")]
	public partial class VW_REQUEST_BARGING
	{
		
		private int _ID;
		
		private int _ID_USER;
		
		private string _NAMA;
		
		private string _CUSTOMER;
		
		private string _JETTY;
		
		private string _TUG_BOAT;
		
		private string _BARGE;
		
		private System.Nullable<int> _CAPACITY;
		
		private string _VESSEL;
		
		private System.Nullable<System.DateTime> _DATE_BOOKING;
		
		private System.Nullable<System.DateTime> _FINISH_BOOKING;
		
		private System.Nullable<int> _PROCESS_TIME;
		
		private System.Nullable<int> _START_TIME;
		
		private System.Nullable<int> _FINISH_TIME;
		
		private string _STATUS;
		
		public VW_REQUEST_BARGING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER", DbType="VarChar(50)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JETTY", DbType="VarChar(50)")]
		public string JETTY
		{
			get
			{
				return this._JETTY;
			}
			set
			{
				if ((this._JETTY != value))
				{
					this._JETTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUG_BOAT", DbType="VarChar(50)")]
		public string TUG_BOAT
		{
			get
			{
				return this._TUG_BOAT;
			}
			set
			{
				if ((this._TUG_BOAT != value))
				{
					this._TUG_BOAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARGE", DbType="VarChar(50)")]
		public string BARGE
		{
			get
			{
				return this._BARGE;
			}
			set
			{
				if ((this._BARGE != value))
				{
					this._BARGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this._CAPACITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VESSEL", DbType="VarChar(200)")]
		public string VESSEL
		{
			get
			{
				return this._VESSEL;
			}
			set
			{
				if ((this._VESSEL != value))
				{
					this._VESSEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_BOOKING", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_BOOKING
		{
			get
			{
				return this._DATE_BOOKING;
			}
			set
			{
				if ((this._DATE_BOOKING != value))
				{
					this._DATE_BOOKING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_BOOKING", DbType="Date")]
		public System.Nullable<System.DateTime> FINISH_BOOKING
		{
			get
			{
				return this._FINISH_BOOKING;
			}
			set
			{
				if ((this._FINISH_BOOKING != value))
				{
					this._FINISH_BOOKING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESS_TIME", DbType="Int")]
		public System.Nullable<int> PROCESS_TIME
		{
			get
			{
				return this._PROCESS_TIME;
			}
			set
			{
				if ((this._PROCESS_TIME != value))
				{
					this._PROCESS_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_TIME", DbType="Int")]
		public System.Nullable<int> START_TIME
		{
			get
			{
				return this._START_TIME;
			}
			set
			{
				if ((this._START_TIME != value))
				{
					this._START_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_TIME", DbType="Int")]
		public System.Nullable<int> FINISH_TIME
		{
			get
			{
				return this._FINISH_TIME;
			}
			set
			{
				if ((this._FINISH_TIME != value))
				{
					this._FINISH_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_IN_APP_NOTIF_POINS")]
	public partial class TBL_T_IN_APP_NOTIF_POIN
	{
		
		private System.Guid _id;
		
		private string _title;
		
		private string _body;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _url;
		
		private string _androidAppId;
		
		private string _iosAppId;
		
		private string _downloadUrl;
		
		private System.Nullable<bool> _isHasBeenRead;
		
		private string _email;
		
		private System.Nullable<int> _ApprovalType;
		
		private string _ApprovaltId;
		
		public TBL_T_IN_APP_NOTIF_POIN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(200)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="VarChar(200)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this._body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(200)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_androidAppId", DbType="VarChar(50)")]
		public string androidAppId
		{
			get
			{
				return this._androidAppId;
			}
			set
			{
				if ((this._androidAppId != value))
				{
					this._androidAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iosAppId", DbType="VarChar(50)")]
		public string iosAppId
		{
			get
			{
				return this._iosAppId;
			}
			set
			{
				if ((this._iosAppId != value))
				{
					this._iosAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadUrl", DbType="VarChar(50)")]
		public string downloadUrl
		{
			get
			{
				return this._downloadUrl;
			}
			set
			{
				if ((this._downloadUrl != value))
				{
					this._downloadUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isHasBeenRead", DbType="Bit")]
		public System.Nullable<bool> isHasBeenRead
		{
			get
			{
				return this._isHasBeenRead;
			}
			set
			{
				if ((this._isHasBeenRead != value))
				{
					this._isHasBeenRead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalType", DbType="Int")]
		public System.Nullable<int> ApprovalType
		{
			get
			{
				return this._ApprovalType;
			}
			set
			{
				if ((this._ApprovalType != value))
				{
					this._ApprovalType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovaltId", DbType="VarChar(128)")]
		public string ApprovaltId
		{
			get
			{
				return this._ApprovaltId;
			}
			set
			{
				if ((this._ApprovaltId != value))
				{
					this._ApprovaltId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[VW_NOTIF_APPROVAL BARGING]")]
	public partial class VW_NOTIF_APPROVAL_BARGING
	{
		
		private System.Guid _id;
		
		private string _title;
		
		private string _body;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _url;
		
		private string _androidAppId;
		
		private string _iosAppId;
		
		private string _downloadUrl;
		
		private System.Nullable<bool> _isHasBeenRead;
		
		private string _email;
		
		private System.Nullable<int> _ApprovalType;
		
		private string _ApprovaltId;
		
		private int _ID_USER;
		
		public VW_NOTIF_APPROVAL_BARGING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(200)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="VarChar(200)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this._body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(200)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_androidAppId", DbType="VarChar(50)")]
		public string androidAppId
		{
			get
			{
				return this._androidAppId;
			}
			set
			{
				if ((this._androidAppId != value))
				{
					this._androidAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iosAppId", DbType="VarChar(50)")]
		public string iosAppId
		{
			get
			{
				return this._iosAppId;
			}
			set
			{
				if ((this._iosAppId != value))
				{
					this._iosAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadUrl", DbType="VarChar(50)")]
		public string downloadUrl
		{
			get
			{
				return this._downloadUrl;
			}
			set
			{
				if ((this._downloadUrl != value))
				{
					this._downloadUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isHasBeenRead", DbType="Bit")]
		public System.Nullable<bool> isHasBeenRead
		{
			get
			{
				return this._isHasBeenRead;
			}
			set
			{
				if ((this._isHasBeenRead != value))
				{
					this._isHasBeenRead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalType", DbType="Int")]
		public System.Nullable<int> ApprovalType
		{
			get
			{
				return this._ApprovalType;
			}
			set
			{
				if ((this._ApprovalType != value))
				{
					this._ApprovalType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovaltId", DbType="VarChar(128)")]
		public string ApprovaltId
		{
			get
			{
				return this._ApprovaltId;
			}
			set
			{
				if ((this._ApprovaltId != value))
				{
					this._ApprovaltId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_CCTV")]
	public partial class TBL_R_CCTV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAMA;
		
		private string _LINK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnLINKChanging(string value);
    partial void OnLINKChanged();
    #endregion
		
		public TBL_R_CCTV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(MAX)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINK", DbType="VarChar(MAX)")]
		public string LINK
		{
			get
			{
				return this._LINK;
			}
			set
			{
				if ((this._LINK != value))
				{
					this.OnLINKChanging(value);
					this.SendPropertyChanging();
					this._LINK = value;
					this.SendPropertyChanged("LINK");
					this.OnLINKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cusp_get_list_jettyResult
	{
		
		private System.Nullable<long> _id;
		
		private string _name;
		
		public cusp_get_list_jettyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt")]
		public System.Nullable<long> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(1)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class cusp_get_barging_activeResult
	{
		
		private int _ClientTransId;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _Customer;
		
		private string _Barge;
		
		private string _Tug_Boat;
		
		private System.Nullable<double> _Target_Barging;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _EndWeight;
		
		private System.Nullable<double> _StartWeight;
		
		private System.DateTime _StartDate;
		
		private System.Nullable<double> _TPH;
		
		private string _Kode;
		
		private string _Jetty;
		
		private System.Nullable<int> _Status;
		
		private string _Description;
		
		private string _TransNo;
		
		private System.Nullable<int> _ClientTransId1;
		
		private string _TransNo1;
		
		private System.Nullable<double> _volumeProgress;
		
		private System.Nullable<double> _persentasevolumeProgres;
		
		public cusp_get_barging_activeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTransId", DbType="Int NOT NULL")]
		public int ClientTransId
		{
			get
			{
				return this._ClientTransId;
			}
			set
			{
				if ((this._ClientTransId != value))
				{
					this._ClientTransId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="VarChar(50)")]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this._Customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barge", DbType="VarChar(50)")]
		public string Barge
		{
			get
			{
				return this._Barge;
			}
			set
			{
				if ((this._Barge != value))
				{
					this._Barge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tug_Boat", DbType="VarChar(50)")]
		public string Tug_Boat
		{
			get
			{
				return this._Tug_Boat;
			}
			set
			{
				if ((this._Tug_Boat != value))
				{
					this._Tug_Boat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target_Barging", DbType="Float")]
		public System.Nullable<double> Target_Barging
		{
			get
			{
				return this._Target_Barging;
			}
			set
			{
				if ((this._Target_Barging != value))
				{
					this._Target_Barging = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndWeight", DbType="Float")]
		public System.Nullable<double> EndWeight
		{
			get
			{
				return this._EndWeight;
			}
			set
			{
				if ((this._EndWeight != value))
				{
					this._EndWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartWeight", DbType="Float")]
		public System.Nullable<double> StartWeight
		{
			get
			{
				return this._StartWeight;
			}
			set
			{
				if ((this._StartWeight != value))
				{
					this._StartWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPH", DbType="Float")]
		public System.Nullable<double> TPH
		{
			get
			{
				return this._TPH;
			}
			set
			{
				if ((this._TPH != value))
				{
					this._TPH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(10)")]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this._Kode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jetty", DbType="VarChar(30)")]
		public string Jetty
		{
			get
			{
				return this._Jetty;
			}
			set
			{
				if ((this._Jetty != value))
				{
					this._Jetty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(30)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TransNo
		{
			get
			{
				return this._TransNo;
			}
			set
			{
				if ((this._TransNo != value))
				{
					this._TransNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTransId1", DbType="Int")]
		public System.Nullable<int> ClientTransId1
		{
			get
			{
				return this._ClientTransId1;
			}
			set
			{
				if ((this._ClientTransId1 != value))
				{
					this._ClientTransId1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransNo1", DbType="VarChar(10)")]
		public string TransNo1
		{
			get
			{
				return this._TransNo1;
			}
			set
			{
				if ((this._TransNo1 != value))
				{
					this._TransNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volumeProgress", DbType="Float")]
		public System.Nullable<double> volumeProgress
		{
			get
			{
				return this._volumeProgress;
			}
			set
			{
				if ((this._volumeProgress != value))
				{
					this._volumeProgress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persentasevolumeProgres", DbType="Float")]
		public System.Nullable<double> persentasevolumeProgres
		{
			get
			{
				return this._persentasevolumeProgres;
			}
			set
			{
				if ((this._persentasevolumeProgres != value))
				{
					this._persentasevolumeProgres = value;
				}
			}
		}
	}
	
	public partial class cusp_get_barging_detailResult
	{
		
		private int _ClientTransId;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _Customer;
		
		private string _Barge;
		
		private string _Tug_Boat;
		
		private System.Nullable<double> _Target_Barging;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _EndWeight;
		
		private System.Nullable<double> _StartWeight;
		
		private System.DateTime _StartDate;
		
		private System.Nullable<double> _TPH;
		
		private string _Kode;
		
		private string _Jetty;
		
		private System.Nullable<int> _Status;
		
		private string _Description;
		
		private string _TransNo;
		
		private System.Nullable<int> _ClientTransId1;
		
		private string _TransNo1;
		
		private System.Nullable<int> _volumeProgress;
		
		private System.Nullable<int> _persentasevolumeProgres;
		
		public cusp_get_barging_detailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTransId", DbType="Int NOT NULL")]
		public int ClientTransId
		{
			get
			{
				return this._ClientTransId;
			}
			set
			{
				if ((this._ClientTransId != value))
				{
					this._ClientTransId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="VarChar(50)")]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this._Customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barge", DbType="VarChar(50)")]
		public string Barge
		{
			get
			{
				return this._Barge;
			}
			set
			{
				if ((this._Barge != value))
				{
					this._Barge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tug_Boat", DbType="VarChar(50)")]
		public string Tug_Boat
		{
			get
			{
				return this._Tug_Boat;
			}
			set
			{
				if ((this._Tug_Boat != value))
				{
					this._Tug_Boat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target_Barging", DbType="Float")]
		public System.Nullable<double> Target_Barging
		{
			get
			{
				return this._Target_Barging;
			}
			set
			{
				if ((this._Target_Barging != value))
				{
					this._Target_Barging = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndWeight", DbType="Float")]
		public System.Nullable<double> EndWeight
		{
			get
			{
				return this._EndWeight;
			}
			set
			{
				if ((this._EndWeight != value))
				{
					this._EndWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartWeight", DbType="Float")]
		public System.Nullable<double> StartWeight
		{
			get
			{
				return this._StartWeight;
			}
			set
			{
				if ((this._StartWeight != value))
				{
					this._StartWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPH", DbType="Float")]
		public System.Nullable<double> TPH
		{
			get
			{
				return this._TPH;
			}
			set
			{
				if ((this._TPH != value))
				{
					this._TPH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(10)")]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this._Kode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jetty", DbType="VarChar(30)")]
		public string Jetty
		{
			get
			{
				return this._Jetty;
			}
			set
			{
				if ((this._Jetty != value))
				{
					this._Jetty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(30)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TransNo
		{
			get
			{
				return this._TransNo;
			}
			set
			{
				if ((this._TransNo != value))
				{
					this._TransNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTransId1", DbType="Int")]
		public System.Nullable<int> ClientTransId1
		{
			get
			{
				return this._ClientTransId1;
			}
			set
			{
				if ((this._ClientTransId1 != value))
				{
					this._ClientTransId1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransNo1", DbType="VarChar(10)")]
		public string TransNo1
		{
			get
			{
				return this._TransNo1;
			}
			set
			{
				if ((this._TransNo1 != value))
				{
					this._TransNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volumeProgress", DbType="Int")]
		public System.Nullable<int> volumeProgress
		{
			get
			{
				return this._volumeProgress;
			}
			set
			{
				if ((this._volumeProgress != value))
				{
					this._volumeProgress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persentasevolumeProgres", DbType="Int")]
		public System.Nullable<int> persentasevolumeProgres
		{
			get
			{
				return this._persentasevolumeProgres;
			}
			set
			{
				if ((this._persentasevolumeProgres != value))
				{
					this._persentasevolumeProgres = value;
				}
			}
		}
	}
	
	public partial class cusp_get_progress_barging_mobileResult
	{
		
		private System.Nullable<int> _id;
		
		private System.Nullable<int> _barging_id;
		
		private string _nodeDesc;
		
		private string _Company;
		
		private string _Barge;
		
		private string _Boat;
		
		private System.Nullable<int> _Planload;
		
		private System.Nullable<int> _Weight;
		
		private System.Nullable<int> _WeightPercentage;
		
		private System.Nullable<int> _STATUS;
		
		private string _Kode;
		
		public cusp_get_progress_barging_mobileResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barging_id", DbType="Int")]
		public System.Nullable<int> barging_id
		{
			get
			{
				return this._barging_id;
			}
			set
			{
				if ((this._barging_id != value))
				{
					this._barging_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeDesc", DbType="VarChar(56) NOT NULL", CanBeNull=false)]
		public string nodeDesc
		{
			get
			{
				return this._nodeDesc;
			}
			set
			{
				if ((this._nodeDesc != value))
				{
					this._nodeDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barge", DbType="VarChar(50)")]
		public string Barge
		{
			get
			{
				return this._Barge;
			}
			set
			{
				if ((this._Barge != value))
				{
					this._Barge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boat", DbType="VarChar(50)")]
		public string Boat
		{
			get
			{
				return this._Boat;
			}
			set
			{
				if ((this._Boat != value))
				{
					this._Boat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Planload", DbType="Int")]
		public System.Nullable<int> Planload
		{
			get
			{
				return this._Planload;
			}
			set
			{
				if ((this._Planload != value))
				{
					this._Planload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightPercentage", DbType="Int")]
		public System.Nullable<int> WeightPercentage
		{
			get
			{
				return this._WeightPercentage;
			}
			set
			{
				if ((this._WeightPercentage != value))
				{
					this._WeightPercentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(MAX)")]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this._Kode = value;
				}
			}
		}
	}
	
	public partial class cusp_get_last_senselog_realtimeResult
	{
		
		private int _TransId;
		
		private string _NetId;
		
		private System.DateTime _StampDate;
		
		private double _Surface;
		
		private string _Temp;
		
		public cusp_get_last_senselog_realtimeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransId", DbType="Int NOT NULL")]
		public int TransId
		{
			get
			{
				return this._TransId;
			}
			set
			{
				if ((this._TransId != value))
				{
					this._TransId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetId", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string NetId
		{
			get
			{
				return this._NetId;
			}
			set
			{
				if ((this._NetId != value))
				{
					this._NetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StampDate", DbType="DateTime NOT NULL")]
		public System.DateTime StampDate
		{
			get
			{
				return this._StampDate;
			}
			set
			{
				if ((this._StampDate != value))
				{
					this._StampDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surface", DbType="Float NOT NULL")]
		public double Surface
		{
			get
			{
				return this._Surface;
			}
			set
			{
				if ((this._Surface != value))
				{
					this._Surface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temp", DbType="VarChar(50)")]
		public string Temp
		{
			get
			{
				return this._Temp;
			}
			set
			{
				if ((this._Temp != value))
				{
					this._Temp = value;
				}
			}
		}
	}
	
	public partial class cusp_avg_range_senselogResult
	{
		
		private System.Nullable<int> _Jam;
		
		private System.Nullable<System.DateTime> _Tanggal;
		
		private System.Nullable<decimal> _Rata_Rata_Surface;
		
		public cusp_avg_range_senselogResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jam", DbType="Int")]
		public System.Nullable<int> Jam
		{
			get
			{
				return this._Jam;
			}
			set
			{
				if ((this._Jam != value))
				{
					this._Jam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this._Tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rata_Rata_Surface", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> Rata_Rata_Surface
		{
			get
			{
				return this._Rata_Rata_Surface;
			}
			set
			{
				if ((this._Rata_Rata_Surface != value))
				{
					this._Rata_Rata_Surface = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
